config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"

  resources :books do
    resources :notes, only: [:create, :destroy]
  end

  resources :sessions, only: [:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  # rerouting because user will think in terms of login and logout, not
  # sessions. the as lets us refer to it throughout the app however we want
  # we no have login_path/login_url/etc..
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :reviewer
  has_many :notes, dependent: :destroy
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :book
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  has_secure_password
  # says this model now has password virtual attribute (not stored on the db) and expects
  # a password_digest on this model. so when you're creating a user
  # you assign their password to password: (the virtual attribute) not the digest
  # You don't want your pass stored as clear text in the database
  # which is why you use a digest, a one-way hash. Even stronger than
  # encryption since that can be decrypted
  # the system will take the typed in password, encrypt it, and see if
  # they match
  # has_secure_password also enables the authenticate password
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_login
  helper_method :logged_in?, :current_user
  # by setting these as helper methods like this they are available not just
  # to the controllers due to the other controllers inheriting from ApplicationController
  # but to the views as well. Different from the view helpers defined in
  # /helpers

  # how we lock down the app so the pages aren't accessible until you Login
  protected
  # unlike private, this will allow the other controllers to inherit
    def ensure_login
      # always go to login page unless session contains reviewer_id
      redirect_to login_path unless session[:reviewer_id]
    end

    def logged_in?
      session[:reviewer_id] # nil is false
    end

    def current_user
      @current_user ||= Reviewer.find session[:reviewer_id]
      # caches current_user instance variable for this particular request, not
      # in between requests
      # current_user is an instance variable of the ApplicationController which
      # the other controllers inherit from. also accessible in views. called
      # simply with current_user
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = current_user.books.paginate(page: params[:page], per_page: 10)
    # paginate is really just like a custom active record scope.
    # it takes the page parameter (what page should we show) and the per page parameter
    # scoping available books just to current user
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.new
    # adding authorization
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = current_user.books.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_book, only: [:create, :destroy]

  def create
    @note = @book.notes.new note_params
    if @note.save
      redirect_to @book, notice: "Note successfully added!"
    else
      redirect_to @book, alert: "Unable to add a note!"
    end
  end

  def destroy
    @note = @book.notes.find params[:id]
    @note.destroy
    redirect_to @book, notice: "Note deleted!"
  end

  private
  def set_book
    @book = Book.find params[:book_id]
  end

  def note_params
    params.require(:note).permit :title, :note
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_login, only: [:new, :create]
  # don't wanna lock out just these two actions so the user can actually log in!
  def new
    # Login Page - new.html.erb
  end
# browser establishes a type of connection to this particular server i.e. localhost3000
  def create
    reviewer = Reviewer.find_by(name: params[:reviewer][:name])
    password = params[:reviewer][:password]
    # not using strong params

    if reviewer && reviewer.authenticate(password)
      # this methodology seems to assume a uniqueness constraint on reviewer names
      # which makes sense. otherwise, theoretically the same pass and name combo
      # could log someone into totally different accounts
      session[:reviewer_id] = reviewer.id
      # don't want to store alot in session, esp sensitive info. just wanna use
      # their id to look up info to preserve some state for them
      redirect_to root_path, notice: "Logged in successfully"
    else
      redirect_to login_path, alert: "Invalid username/password combination"
    end
  end

  def destroy
    reset_session # wipe out session and everything in it
    # rails helper to wipe out the connection between browser and server
    redirect_to login_path, notice: "You have been logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @books %>
<!-- this is the helper that passes in the params[:page] -->

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="book">
  <%= content_tag :span, "#{@book.name} (#{@book.author})", class: "book-title" %>
  <%= link_to "Edit", edit_book_path(@book) %>
</div>

<div id="notes">
  <%= render @book.notes %>
  <!-- again, rails knows to look at _note partial and make the each block -->
</div>

<div>
  <%= form_for([@book, @book.notes.new]) do |f| %>
  <!-- again, have to use the two resources since it's nested so submit knows to
  go to the nested resource path -->
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :note %>
      <%= f.text_area :note, size: "25x5" %>
    </div>
    <div class="actions">
      <%= f.submit "Add New Note" %>
    </div>
  <% end %>
</div>

<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IReviewed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <div style='float: right;'>
    Logged in as <%= current_user.name %> |
    <%= link_to "Logout", logout_path, method: :delete %>
  </div>
<% end %>

<% flash.each do |key, value| %>
<!-- taking from our flash hash which is just temporary storage. remember, just one
action. -->
  <p id='<%= key %>'><%= value %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<div class="note">
  <div>
    <%= content_tag :span, "#{note.title} (#{time_ago_in_words note.created_at} ago)", class: "note-title" %>
    <!-- time_agon_in_words is a rails helper -->
    <%= link_to "Delete Note", [@book, note], method: :delete %>
    <!-- because note is a nested resource, we now have to supply the parent object -->
    <!-- remember have to pass in method argument to show it's a destroy not a show action -->
  </div>
  <div><%= simple_format note.note %></div>
  <!-- simple_format is another rails helper that displays content with a <br/> tag embedded
  so that it breaks new lines you type in -->
</div>